config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  root 'static_pages#landing_page'
  post 'static_pages/thank_you'
  post 'static_pages/index'
  post 'payments/create'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text|Maven+Pro|Archivo+Narrow|Oleo+Script|Oswald" rel="stylesheet">
  </head>

  <body>
  	<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Buycicles</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right nav-overflow">
            <li class="nav-item"> <%= link_to "Home", root_path %></li>
            <li class="nav-item"><%= link_to "Products", products_path %></li>
            <li class="nav-item"> <%= link_to "About", static_pages_about_path %></li>
            <li class="nav-item"> <%= link_to "Contact", static_pages_contact_path %> </li>
            
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Orders", "/orders" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Logout", destroy_user_session_path, :method => :delete%>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Register", new_user_registration_path %>
                </li>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path %>  
                </li>
              <% end %>
            </li>
          </ul>
          <%= form_tag("/products", method: "get", :class => "navbar-form hidden-sm") do %>
            <div class="form-group">
              <%= text_field_tag(:q, nil, :class => "form-control") %>
              <%= submit_tag("Search", :class => "btn btn-default") %>
            </div>
          <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
	 <% if notice %>
     <p class="notice alert alert-info"><%= notice %></p>
    <% end %>
    <%if alert %>
      <p class="alert alert-info"><%= alert %></p>
    <% end %>
	  	
    <%= yield %>
    <footer class="footer navbar-fixed-bottom">
    	&copy; 2017 Bike Nuremberg
    </footer>


    
  </body>
</html>